name: merchant_app
description: "Aplikasi pengelolaan pendapatan toko e-merchant."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Package untuk melakukan request ke server FastAPI
  http: ^1.1.0

  # Icon standar untuk iOS
  cupertino_icons: ^1.0.8
#untuk grafik
  fl_chart: ^0.65.0
  pdf: ^3.10.8      # Tambahan baru
  printing: ^5.11.1 # Tambahan baru
  intl: ^0.19.0
  google_fonts: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Jika Anda ingin menambahkan aset gambar logo toko nanti:
  # assets:
  #   - assets/logo.png